FITTING_MODEL_NAME = "humanoid_torque"
FITTING_MODEL_SOURCE = "monocular_demos.biomechanics_mjx"

FITTING_COORDINATES = [
    {
        "name": "pelvis_tx",
        "kind": "translation",
        "segment": "pelvis",
        "axis": [1.0, 0.0, 0.0],
        "units": "meters",
        "range": [-500.0, 500.0],
    },
    {
        "name": "pelvis_tz",
        "kind": "translation",
        "segment": "pelvis",
        "axis": [0.0, 0.0, 1.0],
        "units": "meters",
        "range": [-300.0, 300.0],
    },
    {
        "name": "pelvis_ty",
        "kind": "translation",
        "segment": "pelvis",
        "axis": [0.0, 1.0, 0.0],
        "units": "meters",
        "range": [-100.0, 200.0],
    },
    {
        "name": "pelvis_tilt",
        "kind": "rotation",
        "segment": "pelvis",
        "axis": [0.0, 0.0, 1.0],
        "units": "radians",
        "range": [-1.5708, 1.5708],
    },
    {
        "name": "pelvis_list",
        "kind": "rotation",
        "segment": "pelvis",
        "axis": [1.0, 0.0, 0.0],
        "units": "radians",
        "range": [-1.5708, 1.5708],
    },
    {
        "name": "pelvis_rotation",
        "kind": "rotation",
        "segment": "pelvis",
        "axis": [0.0, 1.0, 0.0],
        "units": "radians",
        "range": [-1.5708, 1.5708],
    },
    {
        "name": "hip_flexion_r",
        "kind": "rotation",
        "segment": "right_hip",
        "axis": [0.0, 0.0, 1.0],
        "units": "radians",
        "range": [-0.787, 2.0944],
    },
    {
        "name": "hip_adduction_r",
        "kind": "rotation",
        "segment": "right_hip",
        "axis": [1.0, 0.0, 0.0],
        "units": "radians",
        "range": [-0.524, 0.524],
    },
    {
        "name": "hip_rotation_r",
        "kind": "rotation",
        "segment": "right_hip",
        "axis": [0.0, 1.0, 0.0],
        "units": "radians",
        "range": [-2.0944, 2.0944],
    },
    {
        "name": "knee_angle_r",
        "kind": "rotation",
        "segment": "right_knee",
        "axis": [0.0, 0.0, 1.0],
        "units": "radians",
        "range": [-2.7925, 0.174533],
    },
    {
        "name": "ankle_angle_r",
        "kind": "rotation",
        "segment": "right_ankle",
        "axis": [-0.105014, -0.174022, 0.979126],
        "units": "radians",
        "range": [-1.5708, 1.5708],
    },
    {
        "name": "subtalar_angle_r",
        "kind": "rotation",
        "segment": "right_subtalar",
        "axis": [0.78718, 0.604747, -0.120949],
        "units": "radians",
        "range": [-1.5708, 1.5708],
    },
    {
        "name": "mtp_angle_r",
        "kind": "rotation",
        "segment": "right_toes",
        "axis": [-0.580954, 0.0, 0.813936],
        "units": "radians",
        "range": [-1.5708, 1.5708],
    },
    {
        "name": "hip_flexion_l",
        "kind": "rotation",
        "segment": "left_hip",
        "axis": [0.0, 0.0, 1.0],
        "units": "radians",
        "range": [-0.787, 2.0944],
    },
    {
        "name": "hip_adduction_l",
        "kind": "rotation",
        "segment": "left_hip",
        "axis": [-1.0, 0.0, 0.0],
        "units": "radians",
        "range": [-0.524, 0.524],
    },
    {
        "name": "hip_rotation_l",
        "kind": "rotation",
        "segment": "left_hip",
        "axis": [0.0, -1.0, 0.0],
        "units": "radians",
        "range": [-2.0944, 2.0944],
    },
    {
        "name": "knee_angle_l",
        "kind": "rotation",
        "segment": "left_knee",
        "axis": [0.0, 0.0, 1.0],
        "units": "radians",
        "range": [-2.7925, 0.174533],
    },
    {
        "name": "ankle_angle_l",
        "kind": "rotation",
        "segment": "left_ankle",
        "axis": [0.105014, 0.174022, 0.979126],
        "units": "radians",
        "range": [-1.0472, 1.0472],
    },
    {
        "name": "subtalar_angle_l",
        "kind": "rotation",
        "segment": "left_subtalar",
        "axis": [-0.78718, -0.604747, -0.120949],
        "units": "radians",
        "range": [-1.5708, 1.5708],
    },
    {
        "name": "mtp_angle_l",
        "kind": "rotation",
        "segment": "left_toes",
        "axis": [0.580954, 0.0, 0.813936],
        "units": "radians",
        "range": [-1.0472, 1.0472],
    },
    {
        "name": "lumbar_extension",
        "kind": "rotation",
        "segment": "lumbar",
        "axis": [0.0, 0.0, 1.0],
        "units": "radians",
        "range": [-1.5708, 0.377],
    },
    {
        "name": "lumbar_bending",
        "kind": "rotation",
        "segment": "lumbar",
        "axis": [1.0, 0.0, 0.0],
        "units": "radians",
        "range": [-0.754, 0.754],
    },
    {
        "name": "lumbar_rotation",
        "kind": "rotation",
        "segment": "lumbar",
        "axis": [0.0, 1.0, 0.0],
        "units": "radians",
        "range": [-0.754, 0.754],
    },
    {
        "name": "neck_extension",
        "kind": "rotation",
        "segment": "neck",
        "axis": [0.0, 0.0, 1.0],
        "units": "radians",
        "range": [-1.5708, 0.377],
    },
    {
        "name": "neck_bending",
        "kind": "rotation",
        "segment": "neck",
        "axis": [1.0, 0.0, 0.0],
        "units": "radians",
        "range": [-0.754, 0.754],
    },
    {
        "name": "neck_rotation",
        "kind": "rotation",
        "segment": "neck",
        "axis": [0.0, 1.0, 0.0],
        "units": "radians",
        "range": [-0.754, 0.754],
    },
    {
        "name": "arm_flex_r",
        "kind": "rotation",
        "segment": "right_shoulder",
        "axis": [0.0, 0.0, 1.0],
        "units": "radians",
        "range": [-1.5708, 3.1416],
    },
    {
        "name": "arm_add_r",
        "kind": "rotation",
        "segment": "right_shoulder",
        "axis": [1.0, 0.0, 0.0],
        "units": "radians",
        "range": [-3.1415, 1.5708],
    },
    {
        "name": "arm_rot_r",
        "kind": "rotation",
        "segment": "right_shoulder",
        "axis": [0.0, 1.0, 0.0],
        "units": "radians",
        "range": [-1.5708, 1.5708],
    },
    {
        "name": "elbow_flex_r",
        "kind": "rotation",
        "segment": "right_elbow",
        "axis": [0.226047, 0.022269, 0.973862],
        "units": "radians",
        "range": [-0.3, 2.618],
    },
    {
        "name": "pro_sup_r",
        "kind": "rotation",
        "segment": "right_forearm",
        "axis": [0.056398, 0.998406, 0.001952],
        "units": "radians",
        "range": [-0.6, 3.1415],
    },
    {
        "name": "wrist_flex_r",
        "kind": "rotation",
        "segment": "right_wrist",
        "axis": [0.0, 0.0, 1.0],
        "units": "radians",
        "range": [-1.22173, 1.22173],
    },
    {
        "name": "wrist_dev_r",
        "kind": "rotation",
        "segment": "right_wrist",
        "axis": [1.0, 0.0, 0.0],
        "units": "radians",
        "range": [-0.436332, 0.610865],
    },
    {
        "name": "arm_flex_l",
        "kind": "rotation",
        "segment": "left_shoulder",
        "axis": [0.0, 0.0, 1.0],
        "units": "radians",
        "range": [-1.5708, 3.1416],
    },
    {
        "name": "arm_add_l",
        "kind": "rotation",
        "segment": "left_shoulder",
        "axis": [-1.0, 0.0, 0.0],
        "units": "radians",
        "range": [-3.1415, 1.5708],
    },
    {
        "name": "arm_rot_l",
        "kind": "rotation",
        "segment": "left_shoulder",
        "axis": [0.0, -1.0, 0.0],
        "units": "radians",
        "range": [-1.5708, 1.5708],
    },
    {
        "name": "elbow_flex_l",
        "kind": "rotation",
        "segment": "left_elbow",
        "axis": [-0.226047, -0.022269, 0.973862],
        "units": "radians",
        "range": [-0.3, 2.618],
    },
    {
        "name": "pro_sup_l",
        "kind": "rotation",
        "segment": "left_forearm",
        "axis": [-0.056398, -0.998406, 0.001952],
        "units": "radians",
        "range": [-0.6, 3.1415],
    },
    {
        "name": "wrist_flex_l",
        "kind": "rotation",
        "segment": "left_wrist",
        "axis": [0.0, 0.0, 1.0],
        "units": "radians",
        "range": [-1.22173, 1.22173],
    },
    {
        "name": "wrist_dev_l",
        "kind": "rotation",
        "segment": "left_wrist",
        "axis": [-1.0, 0.0, 0.0],
        "units": "radians",
        "range": [-0.436332, 0.610865],
    },
]


def get_fitting_coordinate_names() -> list[str]:
    return [coordinate["name"] for coordinate in FITTING_COORDINATES]


def build_fitting_payload(kinematics: dict) -> dict:
    return {
        "model": FITTING_MODEL_NAME,
        "source": FITTING_MODEL_SOURCE,
        "xml": "humanoid_torque.xml",
        "coordinates": FITTING_COORDINATES,
        "coordinate_names": get_fitting_coordinate_names(),
        "angles": kinematics.get("angles", []),
        "timestamps": kinematics.get("timestamps", []),
        "notes": [
            "translation coordinates use meters",
            "rotation coordinates use radians",
            "angles[frame][index] follows coordinate_names[index]",
        ],
    }
